language: python
python: "3.7"

stages:
  - test
  
cache:
  pip: true
  
jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest
